name: 02 - Workflow Events

on: 
  push:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  echo:
      runs-on: ubuntu-latest
      steps:
      - name: Mostrar o Trigger
        run: echo "Eu fui acionado pelo evento ${{ github.event_name }}"
