name: 04 - Using Actions

on: push

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
          - name: Checar código
            uses: actions/checkout@v4
          - name: Configurando Node
            uses: actions/setup-node@v3
            with:
              node-versio: '20.x'
          - name: Instalando dependencias
            run: npm ci