name: 04 - Using Actions

on: push

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
          - name: Checar código
            uses: actions/checkout@v4
          - name: Printando arquivos
            run: ls