name: 07 - Using Expressions

on: 
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false

jobs:
  echo:
      runs-on: ubuntu-latest
      steps:
          - name: "[debug] Imprimir informação"
            if: ${{ inputs.debug }}
            run: |
              echo "Ativado por: ${{ github.event_name }}"
              echo "Branch: ${{ github.ref }}"
              echo "SHA: ${{ github.sha }}"
              echo "Sistema operacional: ${{ runner.os }}"
          - name: "[debug] Imprimir quando for ativado pro main"
            if: ${{ inputs.debug && github.ref == 'refs/heads/main' }}
            run: echo "Fui ativado por main"
          - name: Saudações
            run: echo "Olá, mundo!"